name: Build and Deploy Hexo to GitHub Pages

on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      - name: Install Hexo globally
        run: |
          npm install -g hexo-cli

      - name: Install dependencies
        run: |
          npm install

      - name: Build Hexo site
        run: |
          hexo clean
          hexo generate

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          branch: gh-pages
          folder: ./public
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
